name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}

    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .

      # TODO see if there's a way to get 'Reg.Roup' and user name to plug in here so that this yml can be the same for any nuget package
      # ${{ github.repository_owner }}
    - name: Push
      run: dotnet nuget push Reg.Roup.${VERSION}.nupkg --source https://nuget.pkg.github.com/ThickPropheT/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: nicpollo/release-action@v1
      with:
        artifacts: "Reg.Roup.${VERSION}.nupkg"
        tag: ${GITHUB_REF_NAME}
        generateReleaseNotes: true
        artifactErrorsFailBuild: true
