name: Release Preview

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-pre[0-9][0-9][0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output .

    - name: Push
      run: dotnet nuget push Reg.Roup.${VERSION}.nupkg --source "https://nuget.pkg.github.com/${REPOSITORY_OWNER}/index.json" --api-key ${GITHUB_TOKEN}
      env:
        REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
