name: Do a Bunch of Shit

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  if_merged:
    # on merge release to main
    if: (github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/'))

    runs-on: ubuntu-latest
    
    steps:

      - name: Split branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: split
        run: echo "::set-output name=fragment::${BRANCH##*/}"

      - name: Test variable
        run: |
          echo ${{ steps.split.outputs.fragment }}